<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>omni_multitool</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Audio\mixkit-uplifting-flute.wav" />
    <None Remove="Assets\Fonts\Jost-Bold.ttf" />
    <None Remove="Assets\Fonts\Jost-Medium.ttf" />
    <None Remove="Assets\Fonts\Jost-Regular.ttf" />
    <None Remove="Assets\Fonts\Kodchasan-Bold.ttf" />
    <None Remove="Assets\Fonts\Kodchasan-Medium.ttf" />
    <None Remove="Assets\Fonts\Kodchasan-Regular.ttf" />
    <None Remove="Assets\Fonts\materialdesignicons-webfont.ttf" />
    <None Remove="Assets\Fonts\MaterialSymbolsOutlined_28pt-Bold.ttf" />
    <None Remove="Assets\Fonts\MaterialSymbolsOutlined_28pt-Medium.ttf" />
    <None Remove="Assets\Fonts\MaterialSymbolsOutlined_28pt-Regular.ttf" />
    <None Remove="Assets\Images\GlassCube.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Audio\mixkit-uplifting-flute.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\Jost-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\Jost-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\Jost-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\Kodchasan-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\Kodchasan-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\materialdesignicons-webfont.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\MaterialSymbolsOutlined_28pt-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\MaterialSymbolsOutlined_28pt-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\MaterialSymbolsOutlined_28pt-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\GlassCube.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\ImgConverter\" />
    <Folder Include="Features\UnitConverter\" />
    <Folder Include="Features\AutoKeyboard\" />
    <Folder Include="Features\ColorPicker\" />
    <Folder Include="Features\AutoClicker\" />
  </ItemGroup>

</Project>
